//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuietHoursSettings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quiet Hours Settings - https://github.com/TwoUnderscorez/QuietHoursSettings\r\n====" +
            "=================================================\r\n\r\nBSD 3-Clause License\r\n=====" +
            "=========\r\n\r\n\r\nCopyright (c) 2017, Ron Yutkin\r\n\r\nAll rights reserved.\r\n\r\n\r\n\r\nRed" +
            "istribution and use in source and binary forms, with or without\r\n\r\nmodification," +
            " are permitted provided that the following conditions are met:\r\n\r\n* Redistributi" +
            "ons of source code must retain the above copyright notice, this\r\n\r\n  list of con" +
            "ditions and the following disclaimer.\r\n\r\n* Redistributions in binary form must r" +
            "eproduce the above copyright notice,\r\n\r\n  this list of conditions and the follow" +
            "ing disclaimer in the documentation\r\n\r\n  and/or other materials provided with th" +
            "e distribution.\r\n\r\n* Neither the name of the copyright holder nor the names of i" +
            "ts\r\n\r\n  contributors may be used to endorse or promote products derived from\r\n\r\n" +
            "  this software without specific prior written permission.\r\n\r\nTHIS SOFTWARE IS P" +
            "ROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\r\nAND ANY EXPRESS OR IM" +
            "PLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\r\nIMPLIED WARRANTIES OF MERC" +
            "HANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\r\nDISCLAIMED. IN NO EVENT SH" +
            "ALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE\r\nFOR ANY DIRECT, INDIRECT, IN" +
            "CIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\r\nDAMAGES (INCLUDING, BUT NOT LIMI" +
            "TED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\r\nSERVICES; LOSS OF USE, DATA, OR PROF" +
            "ITS; OR BUSINESS INTERRUPTION) HOWEVER\r\nCAUSED AND ON ANY THEORY OF LIABILITY, W" +
            "HETHER IN CONTRACT, STRICT LIABILITY,\r\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWIS" +
            "E) ARISING IN ANY WAY OUT OF THE USE\r\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE P" +
            "OSSIBILITY OF SUCH DAMAGE.\r\n\r\nThird party notices:\r\n=============\r\n\r\nMetroFramew" +
            "ork - Windows Modern UI for .NET WinForms Applications Copyright (c) 2013 Jens T" +
            "hiel, http://thielj.github.com/MetroFramework Permission is hereby granted, free" +
            " of charge, to any person obtaining a copy of this software and associated docum" +
            "entation files (the \"Software\"), to deal in the Software without restriction, in" +
            "cluding without limitation the rights to use, copy, modify, merge, publish, dist" +
            "ribute, sublicense, and/or sell copies of the Software, and to permit persons to" +
            " whom the Software is furnished to do so, subject to the following conditions: T" +
            "he above copyright notice and this permission notice shall be included in all co" +
            "pies or substantial portions of the Software.\r\n\r\n THE SOFTWARE IS PROVIDED \"AS I" +
            "S\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED " +
            "TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONIN" +
            "FRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY" +
            " CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OT" +
            "HERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR O" +
            "THER DEALINGS IN THE SOFTWARE. \r\n\r\nPortions of this software are (c) 2011 Sven W" +
            "alter, http://github.com/viperneo\r\n")]
        public string aboutdata {
            get {
                return ((string)(this["aboutdata"]));
            }
        }
    }
}
